"""empty message

Revision ID: 328918ddd8a4
Revises: c1e1fc40f7b4
Create Date: 2025-01-11 16:15:31.332302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '328918ddd8a4'
down_revision: Union[str, None] = 'c1e1fc40f7b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'summary',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('articles', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('articles', 'preview',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'preview',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('articles', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('articles', 'summary',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
