"""empty message

Revision ID: 038142eb9081
Revises: 93fdba83a19a
Create Date: 2025-01-27 12:48:41.576094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '038142eb9081'
down_revision: Union[str, None] = '93fdba83a19a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('hc_price', sa.Float(), nullable=False, server_default="9.99"))
    op.add_column('books', sa.Column('pb_price', sa.Float(), nullable=False, server_default="9.99"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'pb_price')
    op.drop_column('books', 'hc_price')
    # ### end Alembic commands ###
