stages:
  - build
  - deploy

build-job:
  stage: build
  script: 
    - docker build -t yassyalil-app:latest ./app

deploy-job:
  stage: deploy
  script:
    - cd /opt/yassyalil
    - docker compose up -d --no-deps app