stages:
  - build
  - deploy

build-job:
  stage: build
  script: 
    - sudo docker build -t yassyalil-app:latest ./app

deploy-job:
  stage: deploy
  script:
    - sudo docker compose up -d --no-deps app