stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - docker build -t yassyalil-app:latest .

deploy-job:
  stage: deploy
  before_script:
    - cp "$ENV" .env
  script:
    - docker compose up -d
  after_script:
    - ls -la
    - cat .env
