stages:
  - build
  - deploy

build-job:
  stage: build
  script: 
    - docker build -t yassyalil-app:latest ./app

deploy-job:
  stage: deploy
  script:
    # - docker compose stop app || true
    # - docker compose rm -sf app || true
    - docker compose up -d --no-deps app