stages:
  - build
  - test
  - deploy


build-job:
  stage: build
  script:
    - docker build -t yassyalil-app:latest .
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'


test-job:
  stage: test
  script:
    - docker run --rm yassyalil-app pytest -s -v
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'


deploy-job:
  stage: deploy
  before_script:
    - cp "$ENV" .env
  script:
    - docker compose up -d
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
