default:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - docker build -t yassyalil-app:latest .

deploy-job:
  stage: deploy
  before_script:
    - cp "$ENV" .env
  script:
    - docker compose up -d
