networks:
  yassyalil:
    external: true

services:

  app:
    image: yassyalil-app:latest
    container_name: app
    restart: unless-stopped
    environment:
      LOG_LEVEL: ${APP_LOG_LEVEL}
    ports:
      - "8000:8000"
    networks:
      - yassyalil
    command: "python src/main.py"
