networks:
  dev:

services:

  app:
    image: yassyalil-app:latest
    container_name: app
    restart: always
    environment:
      LOG_LEVEL: ${APP_LOG_LEVEL}
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - postgres
    networks:
      - dev
    # command: "python -m src.main"

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/backups:/backups
    ports:
      - "15432:5432"
    networks:
      - dev

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app
    networks:
      - dev

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
    depends_on:
      - nginx
    networks:
      - dev
    entrypoint: certbot certonly --webroot --webroot-path=/var/www/certbot --email ziminjulian@gmail.com --agree-tos --no-eff-email --force-renewal -d yassyalil.com -d www.yassyalil.com

