networks:
  yassyalil:
    external: true

services:

  app:
    image: yassyalil-app:latest
    container_name: app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      LOG_LEVEL: ${APP_LOG_LEVEL}
    ports:
      - "8000:8000"
    networks:
      - yassyalil
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    command: sh -c "alembic upgrade head && python src/main.py"

  
  celery:
    image: yassyalil-app:latest
    container_name: celery
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - yassyalil
    # depends_on:
    #   - rabbitmq
    command: celery --app src.tasks.celery_app worker --pool threads --loglevel=INFO
