"""empty message

Revision ID: bf5e87c0b368
Revises: 87397e1cb1db
Create Date: 2025-01-22 14:07:08.805307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf5e87c0b368'
down_revision: Union[str, None] = '87397e1cb1db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('read_time', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'read_time')
    # ### end Alembic commands ###
