"""empty message

Revision ID: 77b12de9a5c6
Revises: 5cb4d5ae0a72
Create Date: 2025-01-09 21:02:05.430332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77b12de9a5c6'
down_revision: Union[str, None] = '5cb4d5ae0a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'title',
        existing_type=sa.VARCHAR(),
        nullable=True
    )
    op.alter_column('reviews', 'text',
        existing_type=sa.VARCHAR(),
        nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'text',
        existing_type=sa.VARCHAR(),
        nullable=False
    )
    op.alter_column('reviews', 'title',
        existing_type=sa.VARCHAR(),
        nullable=False
    )
    # ### end Alembic commands ###
