"""empty message

Revision ID: 3163fc8041b1
Revises: 801f58db6374
Create Date: 2025-06-13 17:41:42.648284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3163fc8041b1'
down_revision: Union[str, None] = '801f58db6374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books_info')
    op.add_column('books', sa.Column('pb_asin', sa.String(), nullable=True))
    op.add_column('books', sa.Column('eb_asin', sa.String(), nullable=True))
    op.drop_column('books', 'aloud_link')
    op.drop_column('books', 'amazon_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('amazon_link', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('books', sa.Column('aloud_link', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('books', 'eb_asin')
    op.drop_column('books', 'pb_asin')
    op.create_table('books_info',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cover', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pages', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('min_age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amazon_link', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('aloud_link', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('eb_price', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'9.99'::double precision"), autoincrement=False, nullable=False),
    sa.Column('pb_price', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'9.99'::double precision"), autoincrement=False, nullable=False),
    sa.Column('pub_date', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='books_info_pkey')
    )
    # ### end Alembic commands ###
