"""empty message

Revision ID: 801f58db6374
Revises: f25c351e336a
Create Date: 2025-05-11 16:58:24.989277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '801f58db6374'
down_revision: Union[str, None] = 'f25c351e336a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('moderated', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('reviews', sa.Column('published', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'published')
    op.drop_column('reviews', 'moderated')
    # ### end Alembic commands ###
