"""empty message

Revision ID: 764b1bdbc8ed
Revises: 038142eb9081
Create Date: 2025-02-04 11:52:43.418234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764b1bdbc8ed'
down_revision: Union[str, None] = '038142eb9081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_info', sa.Column('hc_price', sa.Float(), server_default='9.99', nullable=False))
    op.add_column('books_info', sa.Column('pb_price', sa.Float(), server_default='9.99', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books_info', 'pb_price')
    op.drop_column('books_info', 'hc_price')
    # ### end Alembic commands ###
